use_frameworks!

target 'HDNTextField_Example' do
  pod 'HDNTextField', :path => '../'

  target 'HDNTextField_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
