use_frameworks!

target 'HDNTextField_Example' do
  pod 'HDNTextField', :path => '../'

  target 'HDNTextField_Tests' do
    inherit! :search_paths

    pod 'Quick', :git => 'git@github.com:Quick/Quick.git'
    pod 'Nimble', :git => 'git@github.com:Quick/Nimble.git'
  end
end
